<?php namespace Whip\Tests;
/**
 * Please see the included LICENSE.txt with this source code. If no
 * LICENSE.txt was provided, then all rights for the source code in
 * this file are reserved by Khalifah Khalil Shabazz
 */

use Whip\HtmlForm;
use PHPUnit\Framework\TestCase;

/**
 * Class HtmlFormTest
 *
 * @package \Whip\Tests
 * @coversDefaultClass \Whip\HtmlForm
 */
class HtmlFormTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
